front_homepage:
    path:     /
    defaults: { _controller: frontBundle:Default:index }

zana_tsampana_onglet:
    path:     /zana-tsampana
    defaults: { _controller: frontBundle:sampana:zanaTsampanaGet }
    
zana_tsampana_containt:
    path:     /zana-tsampana-containt
    defaults: { _controller: frontBundle:sampana:zanaTsampanaContaint }
    
front_index:
    resource: "@frontBundle/Controller/IndexController.php"
    type:     annotation
    
front_fampianarana:
    resource: "@frontBundle/Controller/FampianaranaController.php"
    type:     annotation
    
front_fandaharana:
    resource: "@frontBundle/Controller/FandaharanaController.php"
    type:     annotation
    
front_rafitra:
    resource: "@frontBundle/Controller/RafitraController.php"
    type:     annotation

#article Controller
article_test:
    path:     /article
    defaults: { _controller: frontBundle:Article:index }