front_homepage:
    path:     /
    defaults: { _controller: frontBundle:Default:index }
    
front_index:
    resource: "@frontBundle/Controller/IndexController.php"
    type:     annotation
    
front_fampianarana:
    resource: "@frontBundle/Controller/FampianaranaController.php"
    type:     annotation
    
front_fandaharana:
    resource: "@frontBundle/Controller/FandaharanaController.php"
    type:     annotation
    
front_rafitra:
    resource: "@frontBundle/Controller/RafitraController.php"
    type:     annotation
    
front_tetik_asa:
    resource: "@frontBundle/Controller/TetikAsaController.php"
    type:     annotation
    
front_articlef:
    resource: "@frontBundle/Controller/ArticleController.php"
    type:     annotation
    
front_fifandraisana:
    resource: "@frontBundle/Controller/FifandraisanaController.php"
    type:     annotation
    
front_tsiahy:
    resource: "@frontBundle/Controller/TsiahyController.php"
    type:     annotation