# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        login:
            pattern: ^/login$
            anonymous: true
        
        main:
            pattern: ^/admin/
            anonymous: false
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path : true
                default_target_path: /admin
                use_referer : true
            logout:
                path: fos_user_security_logout
                target: /login
            remember_me:
                key: %secret%
 
    encoders:
        UserBundle\Entity\User: sha512
    
    role_hierarchy:
        ROLE_ADMIN: [ROLE_AUTEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]