back_homepage:
    path:     /admin
    defaults: { _controller: backBundle:Default:index }

back_info:
    resource: "@backBundle/Controller/InfoController.php"
    type:     annotation
    
back_sampana:
    resource: "@backBundle/Controller/SokajinAsaController.php"
    type:     annotation
    
back_personne:
    resource: "@backBundle/Controller/PersonneController.php"
    type:     annotation

back_membre_bureau:
    resource: "@backBundle/Controller/MembreBureauController.php"
    type:     annotation
    
back_article:
    resource: "@backBundle/Controller/ArticleController.php"
    type:     annotation
    
back_zana_tsampana:
    resource: "@backBundle/Controller/ZanaTsampanaController.php"
    type:     annotation
    
back_album:
    resource: "@backBundle/Controller/AlbumController.php"
    type:     annotation