back_homepage:
    path:     /
    defaults: { _controller: backBundle:Default:index }

back_info:
    resource: "@backBundle/Controller/InfoController.php"
    type:     annotation
    
back_sampana:
    resource: "@backBundle/Controller/SokajinAsaController.php"
    type:     annotation