services:
#    back.example:
#        class: backBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    testService:
        class: backBundle\Services\Test
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
            
    typeInfoService:
        class: backBundle\Services\TypeInfoService
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
            
    infoService:
        class: backBundle\Services\InfoService
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
    
    sokajinAsaService:
        class: backBundle\Services\SokajinAsaService
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
            
    personneService:
        class: backBundle\Services\PersonneService
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
    
    articleService:
        class: backBundle\Services\ArticleService
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
    
    zanaTsampanaService:
        class: backBundle\Services\ZanaTsampanaService
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
            
    imageUploader:
        class: backBundle\Services\UploadImages
        arguments: ['%uploadImageDirectory%']