services:
#    back.example:
#        class: backBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    testService:
        class: backBundle\Services\Test
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"