<?php

namespace backBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllByType($type)
    {
        $em = $this->_em;
        $query = $em->createQuery(
            "SELECT article
            FROM backBundle:Article article
            WHERE article.type = '$type'
            "
        );

        $article = $query->getResult();
        
        return $article;
    }
}
