<?php

namespace backBundle\Repository;

use Doctrine\ORM\Query\ResultSetMapping;
/**
 * InfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getAllByType($type)
    {
        $em = $this->_em;
        $query = $em->createQuery(
            "SELECT info
            FROM backBundle:Info info
            WHERE info.type = '$type'
                order by DATE_DIFF( info.date, CURRENT_DATE()) asc
            "
        );

        $info = $query->getResult();
        
        return $info;
    }
    
    public function getLastByType($type)
    {
        $em = $this->_em;
        $dql = "SELECT info
            FROM backBundle:Info info
            WHERE info.type = '$type' and DATE_DIFF( info.date, CURRENT_DATE())>=0
                order by DATE_DIFF( info.date, CURRENT_DATE()) asc";
        
        $query = $em->createQuery($dql);

        $info = $query->getResult();
        
        return $info;
    }
    
    public function getLastTenByType($type)
    {
        $em = $this->_em;
        $dql = "SELECT info
            FROM backBundle:Info info
            WHERE info.type = '$type'
                order by info.date desc";

        $query = $em->createQuery($dql)
                        ->setFirstResult(0)
                        ->setMaxResults(10);
        
        $info = $query->getResult();
        
        return $info;
    }
    
    public function getLastNews()
    {
        $em = $this->_em;
        $query = $em->createQuery(
            "SELECT info
            FROM backBundle:Info info
            WHERE info.type != 'lohahevitra' and info.type != 'vanimpotoana'
                and info.type != 'zioga' and info.type != 'perikopa' 
                and DATE_DIFF(info.date, CURRENT_DATE())>=0
                order by DATE_DIFF( info.date, CURRENT_DATE()) asc
            "
        );

        $info = $query->getResult();
        
        return $info;
    }
    
    public function getLastTenNews()
    {
        $em = $this->_em;
        $query = $em->createQuery(
            "SELECT info
            FROM backBundle:Info info
            WHERE info.type != 'lohahevitra' and info.type != 'vanimpotoana'
                and info.type != 'zioga' and info.type != 'perikopa' 
                order by info.date desc
            "
        )->setFirstResult(0)
         ->setMaxResults(10);

        $info = $query->getResult();
        
        return $info;
    }
    
    public function getLohahevitra()
    {
        $rsm = new ResultSetMapping();
        $rsm->addEntityResult('\backBundle\Entity\Info', 'd');
        $rsm->addFieldResult('d', 'id', 'id');
        $rsm->addFieldResult('d', 'texte', 'texte');
        $rsm->addFieldResult('d', 'titre', 'titre');
        $rsm->addFieldResult('d', 'date', 'date');
        
        $sql = "SELECT info.id as id, info.texte as texte, info.titre as titre, info.date as date "
                . "FROM info as info WHERE info.type = 'lohahevitra' "
                . "and (MONTH(info.date) - MONTH(CURRENT_DATE))=0 and (year(date) - year(CURRENT_DATE))=0";
        
        $query = $this->_em->createNativeQuery($sql, $rsm);

        $lohahevitra = $query->getResult();
        
        if (sizeof($lohahevitra)>0)
        {
            return $lohahevitra[0];
        }
        
        return null;
    }
    
    public function getLastOneInfoByType($type)
    {
        $em = $this->_em;
        $dql = "SELECT info
            FROM backBundle:Info info
            WHERE info.type = '$type' and CURRENT_DATE()>=info.date
                order by info.date desc";
        
        $query = $em->createQuery($dql)
                        ->setFirstResult(0)
                        ->setMaxResults(1);

        $info = $query->getResult();
        
        return $info;
    }
}
