<?php

namespace backBundle\Repository;

/**
 * IsaSokajyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IsaSokajyRepository extends \Doctrine\ORM\EntityRepository
{
    public function findIsaSokajy($idSokajy)
    {
        $em = $this->_em;
        $query = $em->createQuery(
            "SELECT isa
            FROM backBundle:IsaSokajy isa
            WHERE isa.sokajinAsaId = $idSokajy
                and isa.status = 1
            "
        );

        $isa = $query->getResult();
        
        return $isa;
    }
    
    public function findIsaZanany($idZanany)
    {
        $em = $this->_em;
        $query = $em->createQuery(
            "SELECT isa
            FROM backBundle:IsaSokajy isa
            WHERE isa.zanaTsampanaId = $idZanany
                and isa.status = 1
            "
        );

        $isa = $query->getResult();
        
        return $isa;
    }
}