<?php

namespace backBundle\Repository;

/**
 * MembreBureauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreBureauRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySokajinAsa($idSokajinAsa)
    {
        $em = $this->_em;
        
        $query = $em->createQuery(
            "SELECT membre
            FROM backBundle:MembreBureau membre
            WHERE membre.status=1 and membre.idSokajinAsa=$idSokajinAsa
            "
        );

        $sokajy = $query->getSingleResult();
        
        return $sokajy;
    }
    
    public function findByZanaTsampana()
    {
        
    }
}
