<?php

namespace backBundle\Repository;

/**
 * MembreBureauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreBureauRepository extends \Doctrine\ORM\EntityRepository
{
}
