<?php

namespace backBundle\Repository;

/**
 * SokajinAsaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SokajinAsaRepository extends \Doctrine\ORM\EntityRepository
{
}
