<?php

namespace backBundle\Repository;

/**
 * SokajinAsaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SokajinAsaRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllByType($type)
    {
        $em = $this->_em;
        $query = $em->createQuery(
            "SELECT sokajy
            FROM backBundle:SokajinAsa sokajy
            WHERE sokajy.type = '$type'
            "
        );

        $article = $query->getResult();
        
        return $article;
    }
}
