<?php

namespace backBundle\Repository;

/**
 * Type_ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_ArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
