<?php
//
//namespace backBundle\Repository;
//
///**
// * Type_SokajinAsaRepository
// *
// * This class was generated by the Doctrine ORM. Add your own custom
// * repository methods below.
// */
//class Type_SokajinAsaRepository extends \Doctrine\ORM\EntityRepository
//{
//}
