<?php

namespace backBundle\Repository;

/**
 * VisiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteRepository extends \Doctrine\ORM\EntityRepository
{
    public function addVisite()
    {
        $sql = "UPDATE visite SET isa = isa+1";
      
        $stmt = $this->_em->getConnection()->prepare($sql);
        $stmt->execute();
    }
}
