<?php

namespace backBundle\Repository;

/**
 * ZanaTsampanaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZanaTsampanaRepository extends \Doctrine\ORM\EntityRepository
{
}
